### ISSUE TITLE
Unable to download mods

### ISSUE THREAD

**Issue by dramich** [TOLoneWolf/curseDownloader#1]
Attempting to download the FTBPresentsDirewolf20110-1.1.4-1.10.2 manifest and receiving the below error for all mods. Trying to access the below URL in a browser also gives me an error of being not found. 

`[1/71] MISSING FILE SIZE
[1/71] ERROR FILE MISSING FROM SOURCE
https://minecraft.curseforge.com/mc-mods/223794/files/2351885/download
`

**Comment by dramich** [comment]
I saw you pushed an update which I fixed locally. Thanks!

**Comment by TOLoneWolf** [comment]
Yep np. was waiting on my slow internet to upload the compiled version lol.
