### ISSUE TITLE
not downloading proper mods, only downloading a file "Download"

### ISSUE THREAD

**Issue by Grand-Trizmo** [TOLoneWolf/curseDownloader#2]
basically skipping mods and downloading a 404page from curse as shown in this issue https://github.com/portablejim/curseDownloader/issues/36

**Comment by TOLoneWolf** [comment]
Screen shots of this download/error display from the console window so i can see what's going on for you would be helpful information.

Make sure your running the latest version as I'm pretty sure your using an older version as I fixed the link used to download the mods a few weeks ago in https://github.com/TOLoneWolf/curseDownloader/issues/1 and seems to be working fine for me.

**Comment by Grand-Trizmo** [comment]
here is what the console window shows 
https://i.gyazo.com/025428a266f2eb20f71edf28db8cba9e.png
here is what the file it downloads looks like
http://pastebin.grandtrizmo.com/vafohawote.xml

**Comment by TOLoneWolf** [comment]
Alright thanks for the extra info.

**Comment by TOLoneWolf** [comment]
Clear or move your cache directory (path is shown at the top of the log) and try downloading the pack again.

**Comment by Grand-Trizmo** [comment]
thanks all working now :)
