### ISSUE TITLE
Most mods get downloaded, but rarely some are missing...

### ISSUE THREAD

**Issue by Karrq** [TOLoneWolf/curseDownloader#3]
I tried downloading a few packs recently and I had a problem with 2 of them. At first I thought it was probably a curse issue, but their client worked fine. I tried to dig a bit and I found that the files that the downloader couldn't get weren't there, so I had to get them from my friends, who were using the curse launcher. 

Can it be done ?

ex: Try downloading Nuts and Bolts:Torqued v1.6.4.7.... You won't be able to download 2 mods (if not cached, ofc):
- https://minecraft.curseforge.com/projects/eleccore-rendering-library/files/2408169/download
- https://minecraft.curseforge.com/projects/plustic/files/2408230/download

**Comment by TOLoneWolf** [comment]
Yeah I have noticed that with a few mods my self. It happens when the mod author removes that version from download on their curse page. The file it self remains on the server but you need the full path to get it. The curse client has some hidden way of fetching that list of hidden file paths that i haven't seen anywhere in the logs yet so their is no way of finding it atm.

**Comment by TOLoneWolf** [comment]
Found out multiMC supports unpacking cursepack zip files as well, so if your using that as your client it works fine in there directly. Now just to find out how they are doing it to add to this..
http://i.imgur.com/LAOv9RQ.png

**Comment by Karrq** [comment]
Doesn't really work for zip files downloaded from the curse website (at least for me, i just tried it)

**Comment by TOLoneWolf** [comment]
Ah forgot I was on the beta branch of MultiMC might be why.

I added in a section that will use an alternate way of searching for the mod if the default way fails, so it should work now.

**Comment by Karrq** [comment]
Works! I'll test with multiple packs. Great ^^
