### ISSUE TITLE
Please set user agent when using cursemeta.dries007.net

### ISSUE THREAD

**Issue by dries007** [TOLoneWolf/curseDownloader#4]
Hi,

I'd like everyone using CurseMeta (with automated tools) to set there user agent string to something I can identify. (As I request in the [usage info](https://cursemeta.dries007.net/devinfo).)
I apologize If I've missed it, I've just skimmed over the code.

Thanks in advance.

**Comment by TOLoneWolf** [comment]
Sorry about that. Not very familiar with how http(s) requests works. Still learning how to code.
I added this in:
https://github.com/TOLoneWolf/curseDownloader/blob/87310201f9c5ef10f70b597323b16040e136d72d/downloader.py#L23-L25
I believe this should provide what you requested if i understand correctly.

**Comment by dries007** [comment]
That's great! Thanks.

**Comment by dries007** [comment]
You don't have to pre-pend the 'Python-requests', so it's less long, but it is correct so you don't have to change it.

**Comment by TOLoneWolf** [comment]
Good to know. Thanks.
